import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by Ecommerce",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-center" richColors />
        <div className="flex flex-col w-full items-center justify-center bg-zinc-50 font-sans dark:bg-black">
          <div className="w-full">
            <Navbar />
            {/* 如果你的 Navbar 已經加上了 border-b，這裡的 hr 也可以考慮移除讓畫面更乾淨 */}
            <div className="flex justify-center">
              <hr className="w-[95%]" />
            </div>
          </div>

          {/* 移除了 pt-0 md:pt-16，讓內容直接貼齊上方 */}
          <main className="flex min-h-full w-full flex-col items-center justify-between px-0 md:px-8 bg-white dark:bg-black sm:items-start">
            <Providers>{children}</Providers>
          </main>
        </div>
      </body>
    </html>
  );
}
